"""
Shared state definition for the LangGraph multi-agent system.
"""

from typing import TypedDict

class AgentState(TypedDict):
    input: str                 # User's requirements or code snippet
    mode: str                  # "greenfield" or "brownfield"
    readme_content: str        # Extracted README.md for project topic context
    past_memory: str           # Retrieved architectural memory from vector DB
    ast_summary: str           # Parsed structural graph of the codebase
    analysis_report: str       # Generated by Code Analysis Agent
    architecture_plan: str     # Generated by Architecture Agent
    nfr_context: str           # User NFR sliders / project meta (from API or CLI)
    results: dict              # Pydantic structured output from LLM
    error_state: str           # For validation loops
