"""
Shared state definition for the LangGraph multi-agent system.
"""

from typing import TypedDict

class AgentState(TypedDict):
    input: str                 # User's requirements or code snippet
    mode: str                  # "greenfield" or "brownfield"
    readme_content: str        # Extracted README.md for project topic context
    past_memory: str           # Retrieved architectural memory from vector DB
    ast_summary: str           # Parsed structural graph of the codebase
    project_inventory: str     # Tech stack / folder inventory (brownfield)
    deep_brownfield_analysis: str  # Static analysis JSON/text for brownfield
    detected_tech_stack: str  # Deterministic tech stack JSON (brownfield)
    analysis_report: str       # Generated by Analysis Agent (markdown)
    analysis_insights: dict    # Structured extraction from Analysis Agent
    architecture_plan: str     # Generated by Architecture Agent
    nfr_context: str           # User NFR sliders / project meta (from API or CLI)
    results: dict              # ArchitectureOutput (components, layers, risks)
    structured_output: dict    # Mode-specific frontend payload (greenfield/brownfield)
    error_state: str           # For validation loops
